""" Defaults file for the deprecated ip.py """

from django.conf import settings
from .defaults import DEFAULT_IPWARE_META_PRECEDENCE_ORDER, DEFAULT_IPWARE_PRIVATE_IP_PREFIX, DEFAULT_IPWARE_LOOPBACK_PREFIX


IPWARE_META_PRECEDENCE_ORDER = getattr(settings, 'IPWARE_META_PRECEDENCE_ORDER', DEFAULT_IPWARE_META_PRECEDENCE_ORDER)

IPWARE_PRIVATE_IP_PREFIX = getattr(settings, 'IPWARE_PRIVATE_IP_PREFIX', DEFAULT_IPWARE_PRIVATE_IP_PREFIX)

IPWARE_LOOPBACK_PREFIX = DEFAULT_IPWARE_LOOPBACK_PREFIX

IPWARE_NON_PUBLIC_IP_PREFIX = IPWARE_PRIVATE_IP_PREFIX + IPWARE_LOOPBACK_PREFIX
